# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Jay's Tech Note
tagline:          'Some Python, Django and JS Notes'
description:      'My learning path to be a better person'
url:              http://sdlfkorg.github.io
baseurl:          '/sdlfkorg.github.io/'

author:
  name:           'Jay Liao'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sdlfkorg/


