# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Shao-Jen's Tech Note
tagline:          'Live longer live better'
description:      'prepare for transfer (maybe)'
baseurl:          /

author: Jay Liao
name: 'Jay Liao'
url: http://sdlfkorg.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sdlfkorg/


